import {describe,expect,it} from 'vitest';
import {GraphicsRecovery,isExpectedGraphicsCancellation} from '../src/render/graphics-recovery';

describe('graphics recovery state',()=>{
  it('records a bounded successful restoration and requested driving return',()=>{const state=new GraphicsRecovery();expect(state.isReady()).toBe(true);const token=state.begin(100,true);expect(state.isReady()).toBe(false);expect(state.snapshot()).toMatchObject({phase:'recovering',attempts:1,resumeRequested:true});expect(state.succeed(token,440)).toBe(true);expect(state.isReady()).toBe(true);expect(state.snapshot()).toMatchObject({phase:'ready',durationMs:340,resumeRequested:true,message:''});});
  it('keeps a clear failure terminal when restoration arrives after its deadline',()=>{const state=new GraphicsRecovery(),token=state.begin(10,false);expect(state.fail(token,5010,'Reload required.')).toBe(true);expect(state.succeed(token,6000)).toBe(false);expect(state.snapshot()).toMatchObject({phase:'failed',attempts:1,resumeRequested:false,durationMs:5000,message:'Reload required.'});});
  it('rejects stale timeout and restore callbacks after a newer loss',()=>{const state=new GraphicsRecovery(),first=state.begin(0,true),second=state.begin(25,false);expect(state.fail(first,100,'stale')).toBe(false);expect(state.succeed(first,110)).toBe(false);expect(state.snapshot()).toMatchObject({phase:'recovering',attempts:2,resumeRequested:false});expect(state.succeed(second,125)).toBe(true);});
  it('recognizes only the expected lost-device readback cancellation across error realms',()=>{const cancellation=new DOMException("Failed to execute 'mapAsync' on 'GPUBuffer': Buffer was unmapped before mapping was resolved.",'AbortError'),foreign={name:'AbortError',message:cancellation.message};expect(isExpectedGraphicsCancellation(cancellation,true)).toBe(true);expect(isExpectedGraphicsCancellation(foreign,true)).toBe(true);expect(isExpectedGraphicsCancellation(cancellation,false)).toBe(false);expect(isExpectedGraphicsCancellation(new DOMException('World load cancelled','AbortError'),true)).toBe(false);expect(isExpectedGraphicsCancellation(new Error('render failed'),true)).toBe(false);});
});
