import type { Screen, SaveGame, VehicleState, RaceState, RaceSessionConfig, V3, VehicleDefinition } from '../core/types';
import { VEHICLES, vehicleById } from '../content/vehicles';
import { ROADS, LANDMARKS, LAKE, CIRCUIT, regionAt } from '../content/world';
import { formatTime, clamp } from '../core/math';
import { handlingMap } from './handling-map';
import { RACE_RULES } from '../content/race-course';

export interface ViewModel {screen:Screen;save:SaveGame;player:VehicleState;race:RaceState;raceOrder:{name:string;id:string;lap:number;best:number;penalty:number;finished:boolean;finishTime:number}[];raceStage:number;raceConfig:RaceSessionConfig;mode:string;renderer:string;fps:number;cells:number;drawCalls:number;triangles:number;wetness:number;clock:number;route:V3[];destination:string|null;mapSelection:string|null;activity:{name:string;time:number;score:number}|null;message:string;storageError:string;pausedFromDrive:boolean;trafficCount:number;physicsMs:number;}
export type UIAction=(action:string,value?:string)=>void;
const paths:Record<string,string>={drive:'M3 17h18M5 17l1-8h12l1 8M7 9l2-4h6l2 4M7 17v3m10-3v3M7 13h2m6 0h2',flag:'M5 22V3m0 0c5-4 9 4 15 0v10c-6 4-10-4-15 0',garage:'M3 21V9l9-6 9 6v12M7 21V11h10v10M7 15h10m-10 3h10',map:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2zM9 3v16m6-14v16',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',pin:'M12 22s8-8 8-13a8 8 0 0 0-16 0c0 5 8 13 8 13zM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',wrench:'M14 5a6 6 0 0 0 5 9L9 23l-4-4 9-10a6 6 0 0 1 0-4',sound:'M3 9h4l5-5v16l-5-5H3zM16 7a7 7 0 0 1 0 10m3-13a11 11 0 0 1 0 16'};
export const icon=(name:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]??paths.drive}"/></svg>`;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const logo='<svg class="brand-symbol" viewBox="0 0 54 38"><path d="M1 36 20 3 29 19 35 9 53 36H39l-9-15-6 10-5-10-9 15z" fill="currentColor"/></svg>';
function silhouette(v:VehicleDefinition,color:string){return `<svg class="car-silhouette" viewBox="0 0 240 80"><ellipse cx="120" cy="65" rx="101" ry="8" fill="#000" opacity=".35"/><path d="${v.class==='FORMULA'?'M14 51 60 44 83 42 91 28 126 30 134 40 188 48 223 51 220 58H17z':'M18 50 36 39 72 34 92 16 151 17 179 37 218 44 225 59 18 61z'}" fill="${color}"/><path d="M80 34 97 21h49l24 16z" fill="#182d37"/><path d="M24 49h47m100-5 45 6" stroke="#e7edf0" opacity=".6"/><circle cx="59" cy="58" r="16" fill="#0e141b"/><circle cx="183" cy="58" r="16" fill="#0e141b"/><circle cx="59" cy="58" r="9" fill="#82939e"/><circle cx="183" cy="58" r="9" fill="#82939e"/></svg>`;}
const mapPoint=(x:number,z:number)=>`${((x+2100)/4200*900).toFixed(1)},${((2100-z)/4200*900).toFixed(1)}`;
function roadMapSvg(player:VehicleState,route:V3[],destination:string|null,mini=false){
  const p=mapPoint(player.position.x,player.position.z).split(',').map(Number),view=mini?`${p[0]-80} ${p[1]-80} 160 160`:'0 0 900 900';
  return `<svg class="world-map ${mini?'mini':''}" viewBox="${view}" aria-label="Map of Redwood Valley"><defs><pattern id="grid-${mini}" width="45" height="45" patternUnits="userSpaceOnUse"><path d="M45 0H0V45" fill="none" stroke="#ffffff" stroke-opacity=".035"/></pattern></defs><rect x="-300" y="-300" width="1500" height="1500" fill="#17292c"/><path d="M530 40 770 80 850 170 760 380 540 420 370 210z" fill="#293c33"/><path d="M40 580 300 540 350 870 40 900z" fill="#34413e"/><ellipse cx="${(LAKE.x+2100)/4200*900}" cy="${(2100-LAKE.z)/4200*900}" rx="${LAKE.rx/4200*900}" ry="${LAKE.rz/4200*900}" fill="#245568"/><rect width="900" height="900" fill="url(#grid-${mini})"/>${ROADS.map(r=>`<polyline points="${r.points.filter((_,i)=>i%3===0).map(p=>mapPoint(p.x,p.z)).join(' ')}" fill="none" stroke="${r.kind==='circuit'?'#bed1c9':r.kind==='highway'?'#aeb4a8':'#697d75'}" stroke-width="${r.kind==='highway'?4:2.3}" stroke-linejoin="round"/>`).join('')}${route.length?`<polyline points="${route.map(p=>mapPoint(p.x,p.z)).join(' ')}" fill="none" stroke="#79c8ed" stroke-width="${mini?3:4}" stroke-linejoin="round"/>`:''}${!mini?'<g fill="#a6b9ac" font-family="sans-serif" font-size="13" letter-spacing="3"><text x="105" y="710">WESTBROOK</text><text x="490" y="165">RIDGEWAY</text><text x="390" y="330">PINECREST</text><text x="510" y="750">ASTER</text><text x="160" y="320" fill="#88b5c6">LAKE AURELIA</text></g>':''}${LANDMARKS.filter(l=>!mini||['garage','service','scenic'].includes(l.type)).map(l=>{const c=mapPoint(l.x,l.z).split(',');return `<g class="map-marker ${destination===l.id?'chosen':''}" data-action="map-select" data-value="${l.id}" tabindex="${mini?-1:0}" role="button" aria-label="${esc(l.name)}"><circle cx="${c[0]}" cy="${c[1]}" r="${mini?4:9}" fill="${l.type==='circuit'?'#c8a9e6':l.type==='speed'?'#d8b773':l.type==='scenic'?'#8dbba0':'#8bc3e4'}" stroke="#15242a" stroke-width="2"/>${!mini?`<text x="${Number(c[0])+14}" y="${Number(c[1])+4}" fill="#e7eee9" font-family="sans-serif" font-size="10">${esc(l.name)}</text>`:''}</g>`;}).join('')}<g transform="translate(${p[0]},${p[1]}) rotate(${player.yaw*180/Math.PI})"><path d="M0-7 5 6 0 3-5 6z" fill="#eefaff" stroke="#69bfe9" stroke-width="2"/></g></svg>`;
}
export function mapSvg(player:VehicleState,route:V3[],destination:string|null,mini=false){
  // Insert the private test pad above terrain but below public roads, routes and markers.
  return roadMapSvg(player,route,destination,mini).replace('<polyline',handlingMap(mapPoint)+'<polyline');
}
export class Interface {
  private screen:Screen|null=null;private frame=0;private model:()=>ViewModel;
  constructor(private root:HTMLElement,getModel:()=>ViewModel,private action:UIAction){this.model=getModel;root.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLElement>('[data-action]');if(b)this.action(b.dataset.action!,b.dataset.value);});root.addEventListener('change',e=>{const el=e.target as HTMLInputElement;if(el.dataset.setting)this.action('setting',JSON.stringify({key:el.dataset.setting,value:el.type==='checkbox'?el.checked:el.value}));if(el.dataset.custom)this.action('custom',JSON.stringify({key:el.dataset.custom,value:el.value}));if(el.dataset.race)this.action('race-config',JSON.stringify({key:el.dataset.race,value:el.value}));});root.addEventListener('keydown',e=>{if(e.key==='Enter'){const el=(e.target as Element).closest<HTMLElement>('[data-action]');if(el){e.preventDefault();this.action(el.dataset.action!,el.dataset.value);}}});}
  invalidate(){this.screen=null;}
  render(force=false){const m=this.model();if(!force&&this.screen===m.screen)return;this.screen=m.screen;const v=vehicleById(m.save.selected);
    if(m.screen==='drive'){this.root.innerHTML=this.hud(m);return;}
    const nav=[['home','drive','Free Drive'],['motorsport','flag','Motorsport'],['garage','garage','Garage'],['customize','wrench','Customization'],['map','map','World map'],['settings','settings','Settings']];
    const header=`<header class="topbar"><button class="brand" data-action="screen" data-value="home">${logo}<span>KAIROS<small>FIND YOUR MOMENT</small></span></button><div class="session-badge"><span class="status-dot"></span> REDWOOD VALLEY <span class="divider"></span>${icon('sun')} ${this.time(m.save.settings.time)}</div></header>`;
    const sidebar=`<nav class="sidebar" aria-label="Main navigation">${nav.map(([id,i,label])=>`<button class="nav-item ${m.screen===id?'active':''}" data-action="screen" data-value="${id}">${icon(i)}<span>${label}</span>${m.screen===id?'<i></i>':''}</button>`).join('')}<button id="start-handling" class="nav-item" data-action="handling">${icon('drive')}<span>Handling course</span></button><div class="sidebar-footer">${(m.save.distance/1000).toFixed(1)} KM DRIVEN<small>${m.save.discovered.length} ROADS DISCOVERED</small></div></nav>`;
    let body='';
    if(m.screen==='home')body=`<section class="home-copy"><div class="eyebrow">WELCOME TO REDWOOD VALLEY</div><h1>The road.<br>Your rhythm.</h1><p>Take the long way. Chase the perfect corner.<br>There’s a moment waiting around the next bend.</p><button id="start-drive" class="primary large" data-action="start-drive">${icon('drive')} Take the wheel ${icon('arrow')}</button><div class="home-meta">${icon('sun')} ${m.save.settings.weather} skies <span>·</span> ${v.name}</div></section><div class="home-car-label"><span class="eyebrow">READY WHEN YOU ARE</span><h2>${v.name}</h2><p>${v.power} HP <span> / </span> ${v.drive} <span> / </span> ${v.class}</p><button class="text-button" data-action="screen" data-value="garage">Explore your garage ${icon('arrow')}</button></div>`;
    if(m.screen==='garage'||m.screen==='customize')body=`<section class="garage-heading"><div class="eyebrow">YOUR CARS. YOUR CHARACTER.</div><h1>${m.screen==='garage'?'The collection.':'Make it yours.'}</h1></section><aside class="vehicle-card"><div class="vehicle-category">${v.class}<span>0${VEHICLES.indexOf(v)+1} / 06</span></div><h2>${v.name}</h2><p>${v.description}</p>${[['Power',`${v.power} hp`,v.power/850],['0–100 km/h',`${v.zeroTo100} s`,1-v.zeroTo100/10],['Top speed',`${v.topSpeed} km/h`,v.topSpeed/360],['Mechanical grip',v.grip.toFixed(2),v.grip/1.8]].map(([name,val,n])=>`<div class="stat-row"><span>${name}</span><b>${val}</b><i style="--fill:${Number(n)*100}%"></i></div>`).join('')}<div class="car-specs"><span>${v.drive}</span><span>${v.mass.toLocaleString()} kg</span><span>${v.gears.length}-speed</span></div>${m.screen==='customize'?this.customization(m,v):`<button class="text-button" data-action="screen" data-value="customize">${icon('wrench')} Personalize vehicle ${icon('arrow')}</button>`}</aside><section class="car-collection"><div class="collection-title"><span>ALL VEHICLES</span><span>ROAD / GT / OPEN WHEEL</span></div><div class="car-cards">${VEHICLES.map(car=>`<button class="car-card ${v.id===car.id?'selected':''}" data-action="select-car" data-value="${car.id}" aria-label="Select ${car.name}">${silhouette(car,m.save.customization[car.id]?.paint??car.color)}<span>${car.name}<small>${car.class}</small></span></button>`).join('')}</div><div class="garage-actions"><span class="subtle">Every car. A different conversation.</span><button class="primary" data-action="${v.class==='ROAD'?'start-drive':'screen'}" data-value="motorsport">${icon('drive')} ${v.class==='ROAD'?'Drive this car':'Take it to the circuit'} ${icon('arrow')}</button></div></section>`;
    if(m.screen==='motorsport')body=this.motorsport(m);
    if(m.screen==='settings')body=this.settings(m);
    if(m.screen==='map'){const l=LANDMARKS.find(l=>l.id===(m.mapSelection??m.destination))??LANDMARKS[0];body=`<section class="map-layout"><div class="section-heading"><div><span class="eyebrow">A WORLD WORTH GETTING LOST IN</span><h1>Redwood Valley.</h1></div><span>${(ROADS.filter(r=>r.kind!=='pit'&&r.kind!=='test').reduce((s,r)=>s+r.length,0)/1000).toFixed(1)} KM OF OPEN ROAD</span></div><div class="map-container">${mapSvg(m.player,m.route,m.destination)}<div class="map-scale">N ↑ <span>──── 1 km</span></div></div><aside class="map-detail"><span class="eyebrow">${l.type.toUpperCase()}</span><h2>${l.name}</h2><p>${l.description}</p><button class="primary" data-action="navigate" data-value="${l.id}">${icon('pin')} Set route</button>${['trial','drift','speed','scenic'].includes(l.type)?`<button data-action="activity" data-value="${l.id}">Start activity</button>`:''}${l.type==='circuit'?'<button data-action="screen" data-value="motorsport">Enter Motorsport</button>':''}<div class="map-legend"><span><i style="background:#8dbba0"></i>Scenic destinations</span><span><i style="background:#d8b773"></i>Driving activities</span><span><i style="background:#c8a9e6"></i>Motorsport</span></div></aside></section>`;}
    if(m.screen==='pause')body=`<section class="pause-panel"><span class="eyebrow">TAKE A BREATH</span><h1>Your moment<br>can wait.</h1><p>${regionAt(m.player.position.x,m.player.position.z)}</p><button class="primary large" data-action="resume">Resume drive ${icon('arrow')}</button><button data-action="screen" data-value="map">${icon('map')} World map</button><button data-action="screen" data-value="settings">${icon('settings')} Settings</button><button data-action="reset">Reset to road</button>${m.mode!=='Free Drive'?'<button data-action="end-session">End session</button>':''}<button class="text-button" data-action="home">Return to garage</button></section>`;
    if(m.screen==='results')body=this.results(m);
    this.root.innerHTML=`<div class="menu-shade ${m.screen==='map'||m.screen==='settings'?'opaque':''}"></div>${header}${m.screen!=='pause'?sidebar:''}${body}<footer class="bottom-bar"><span>EXPLORE. DRIVE. DISCOVER.</span><span>${m.pausedFromDrive?'<button data-action="resume">ESC · BACK TO DRIVE</button>':'<span class="keycap">W A S D</span> DRIVE <span class="keycap">C</span> CAMERA'}<button class="icon-button" data-action="toggle-sound" aria-label="Toggle audio">${icon('sound')}</button></span></footer><div id="toast" class="toast ${m.message?'visible':''}">${esc(m.message)}</div>`;
  }
  private time(v:number){return `${Math.floor(v).toString().padStart(2,'0')}:${Math.floor(v%1*60).toString().padStart(2,'0')}`;}
  private customization(m:ViewModel,v:VehicleDefinition){const c=m.save.customization[v.id]??{paint:v.color,wheels:'#b2bac0',livery:0,brakeBias:.6,aero:1};return `<div class="custom-options"><label>Paint<input type="color" data-custom="paint" value="${c.paint}"/></label><label>Wheel finish<input type="color" data-custom="wheels" value="${c.wheels}"/></label><label>Livery<select data-custom="livery"><option value="0" ${c.livery===0?'selected':''}>Pure</option><option value="1" ${c.livery===1?'selected':''}>Twin stripe</option><option value="2" ${c.livery===2?'selected':''}>Competition</option></select></label><label>Front brake bias<input type="range" min="0.45" max="0.72" step="0.01" value="${c.brakeBias}" data-custom="brakeBias"/></label>${v.class!=='ROAD'?`<label>Aero balance<input type="range" min="0.6" max="1.4" step="0.05" value="${c.aero}" data-custom="aero"/></label>`:''}</div>`;}
  private motorsport(m:ViewModel){const c=m.raceConfig;return `<section class="motorsport-layout"><div class="eyebrow">ASTER INTERNATIONAL · REDWOOD VALLEY</div><h1>Find the limit.</h1><p class="section-intro">${(CIRCUIT.length/1000).toFixed(2)} km. Three sectors. A thousand ways to improve.</p><div class="race-setup"><div class="circuit-preview"><svg viewBox="250 -1700 1450 1400"><polyline points="${CIRCUIT.points.map(p=>`${p.x},${p.z}`).join(' ')}" fill="none" stroke="#92c9e6" stroke-width="14" stroke-linecap="round"/></svg><div><span class="eyebrow">THE CIRCUIT</span><h2>Aster International</h2><p>A fast opening sector gives way to a technical infield.<br>Stay patient. The lap comes to you.</p></div></div><div class="race-options"><label>Session<select data-race="kind">${['Practice','Qualifying','Quick Race','Race Weekend'].map(k=>`<option ${c.kind===k?'selected':''}>${k}</option>`).join('')}</select></label><label>Vehicle class<select data-race="vehicleClass"><option value="GT" ${c.vehicleClass==='GT'?'selected':''}>GT · GTX-R</option><option value="FORMULA" ${c.vehicleClass==='FORMULA'?'selected':''}>Formula · Apex 01</option></select></label><label>Race distance<select data-race="laps">${[3,5,10,20].map(n=>`<option value="${n}" ${c.laps===n?'selected':''}>${n} laps</option>`).join('')}</select></label><label>Grid size<select data-race="entrants">${[4,8,12,16].map(n=>`<option value="${n}" ${c.entrants===n?'selected':''}>${n} cars</option>`).join('')}</select></label><label>Starting position<select data-race="position">${Array.from({length:c.entrants},(_,i)=>`<option value="${i+1}" ${c.position===i+1?'selected':''}>P${i+1}</option>`).join('')}</select></label><label>AI difficulty<select data-race="difficulty">${[[.35,'Club'],[.65,'Competitive'],[.9,'Expert']].map(([n,label])=>`<option value="${n}" ${c.difficulty===n?'selected':''}>${label}</option>`).join('')}</select></label><button id="start-race" class="primary large" data-action="start-race">${icon('flag')} Enter session ${icon('arrow')}</button></div></div></section>`;}
  private settings(m:ViewModel){const s=m.save.settings;const range=(name:string,key:keyof typeof s,min:number,max:number,step:number)=>`<label>${name}<input type="range" data-setting="${key}" min="${min}" max="${max}" step="${step}" value="${s[key]}"/></label>`;const select=(name:string,key:keyof typeof s,values:string[])=>`<label>${name}<select data-setting="${key}">${values.map(v=>`<option ${s[key]===v?'selected':''}>${v}</option>`).join('')}</select></label>`;const check=(name:string,key:keyof typeof s)=>`<label>${name}<input type="checkbox" data-setting="${key}" ${s[key]?'checked':''}/></label>`;return `<section class="settings-layout"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Your drive. Your way.</h1><div class="settings-grid"><div class="settings-card"><h3>Display & world</h3>${select('Graphics preset','quality',['Low','Medium','High','Ultra'])}${range('Render scale','resolution',.7,1.5,.1)}${select('Weather','weather',['Clear','Cloudy','Overcast','Rain'])}${range('Time of day','time',0,23.9,.1)}${range('Time progression','timeRate',0,60,1)}${range('Traffic density','traffic',0,24,1)}${select('Speed units','units',['mph','km/h'])}</div><div class="settings-card"><h3>Driving & audio</h3>${check('Automatic transmission','automatic')}${check('Anti-lock brakes','abs')}${check('Traction control','tc')}${check('Stability control','esc')}${range('Steering sensitivity','steerSensitivity',.3,1.4,.05)}${range('Controller deadzone','deadzone',0,.35,.01)}${range('Master volume','volume',0,1,.05)}${check('Developer telemetry','showTelemetry')}</div><div class="settings-card"><h3>Controls</h3><div class="bindings">${Object.entries(s.bindings).map(([name,code])=>`<button data-action="bind" data-value="${name}"><span>${name}</span><kbd>${code.replace('Key','')}</kbd></button>`).join('')}</div><p class="subtle">Controller: triggers accelerate / brake. Left stick steers. B camera · X reset · Y map · Menu pause.</p></div></div><div class="settings-bottom"><span class="subtle">${esc(m.storageError||'Your settings and records are saved on this device.')}</span><button data-action="save-export">Export save</button><button data-action="save-import">Import save</button><button class="danger" data-action="reset-save">Reset progress</button></div></section>`;}
  private results(m:ViewModel){
    const timing=m.mode==='Practice'||m.mode==='Qualifying'||m.mode==='Race Weekend'&&m.raceStage<2;
    const leaderLaps=Math.max(0,...m.raceOrder.map(r=>r.lap));
    const rows=m.raceOrder.map((r,i)=>{
      const lapsDown=leaderLaps-r.lap;
      const classification=timing?String(Math.max(0,r.lap-1)):!r.finished?`DNF · ${Math.max(0,r.lap-1)} laps`:lapsDown>0?`+${lapsDown} lap${lapsDown===1?'':'s'}`:formatTime(r.finishTime);
      return `<div class="result-row ${r.id==='player'?'player-row':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${r.name}</span><span>${formatTime(r.best)}</span><span>${r.penalty?`+${r.penalty}s`:'—'}</span><span>${classification}</span></div>`;
    }).join('');
    return `<section class="results-layout"><div class="eyebrow">ASTER INTERNATIONAL · SESSION COMPLETE</div><h1>${timing?'Every lap counts.':'Across the line.'}</h1><p class="section-intro">${m.mode} · ${m.raceConfig.vehicleClass==='FORMULA'?'Formula':'GT'} · ${m.raceConfig.laps} laps</p><div class="results-table"><div class="result-row table-heading"><span>POS</span><span>DRIVER</span><span>BEST LAP</span><span>PENALTY</span><span>${timing?'LAPS':'CLASSIFICATION'}</span></div>${rows}</div><div class="result-actions"><button data-action="home">Back to garage</button><button data-action="retry-race">Run it again</button>${m.mode==='Race Weekend'&&m.raceStage<2?'<button class="primary" data-action="next-session">Continue race weekend →</button>':'<button class="primary" data-action="start-drive">Explore the valley →</button>'}</div></section>`;
  }
  private hud(m:ViewModel){return `<div class="hud-top"><div class="hud-region"><span class="eyebrow" id="region">${regionAt(m.player.position.x,m.player.position.z)}</span><span id="mode-label">${m.mode}</span></div><button class="hud-pause" data-action="pause" aria-label="Pause">Ⅱ</button></div><section class="navigation-widget"><div id="minimap">${mapSvg(m.player,m.route,m.destination,true)}</div><div class="nav-caption"><span id="nav-title">THE ROAD IS YOURS</span><strong id="nav-distance">Explore. Drive. Discover.</strong></div></section><section id="race-hud" class="race-hud" ${m.mode==='Free Drive'?'hidden':''}></section><section id="activity-hud" class="activity-hud"></section><div id="countdown" class="countdown"></div><section class="vehicle-hud"><div class="rev-segments">${Array.from({length:16},(_,i)=>`<i data-rev="${i}"></i>`).join('')}</div><div class="speed-readout"><span id="gear">1</span><strong id="speed">0</strong><span id="unit">mph</span></div><div class="speed-caption"><span id="rpm">950 RPM</span><span id="fuel">60 L</span></div><div class="fuel-bar"><i id="fuel-fill"></i></div></section><section class="assists"><span id="abs-state">ABS</span><span id="tc-state">TCS</span><span id="surface">ASPHALT</span><span id="tire-state"></span></section><div class="drive-controls"><span>ESC <small>PAUSE</small></span><span>M <small>MAP</small></span><span>C <small>CAMERA</small></span><span>R <small>RESET</small></span><button data-action="service">SERVICE / PIT</button></div><pre id="telemetry" hidden></pre><div id="toast" class="toast"></div>`;}
  update(){const m=this.model();if(m.screen!==this.screen)this.render();const toast=this.root.querySelector<HTMLElement>('#toast');if(toast){toast.textContent=m.message;toast.classList.toggle('visible',!!m.message);}if(m.screen!=='drive')return;const p=m.player,v=vehicleById(m.save.selected),s=m.save.settings;
    const text=(id:string,t:string)=>{const el=this.root.querySelector('#'+id);if(el)el.textContent=t;};text('speed',Math.round(Math.abs(p.speed)*(s.units==='mph'?2.23694:3.6)).toString());text('unit',s.units);text('gear',p.gear<0?'R':String(p.gear));text('rpm',`${Math.round(p.rpm/50)*50} RPM`);text('fuel',`${p.fuel.toFixed(1)} L`);text('region',regionAt(p.position.x,p.position.z));text('surface',p.surface.toUpperCase());text('tire-state',`${Math.round(Math.min(...p.wheels.map(w=>w.wear))*100)}% TIRES`);
    this.root.querySelectorAll<HTMLElement>('[data-rev]').forEach((el,i)=>{el.className=p.rpm/v.redline>(i+1)/16?i>12?'lit red':'lit':'';});const fill=this.root.querySelector<HTMLElement>('#fuel-fill');if(fill)fill.style.width=`${p.fuel/v.tank*100}%`;
    this.root.querySelector('#abs-state')?.classList.toggle('working',p.absActive);this.root.querySelector('#tc-state')?.classList.toggle('working',p.tcActive);
    const dest=LANDMARKS.find(l=>l.id===m.destination);text('nav-title',dest?.name.toUpperCase()??'THE ROAD IS YOURS');text('nav-distance',dest?`${(Math.hypot(dest.x-p.position.x,dest.z-p.position.z)/1000).toFixed(1)} km to destination`:'Explore. Drive. Discover.');
    if(this.frame++%5===0){const map=this.root.querySelector('#minimap');if(map)map.innerHTML=mapSvg(p,m.route,m.destination,true);}
    const race=this.root.querySelector('#race-hud');if(race&&m.mode!=='Free Drive'){const r=m.race.entrants[0],position=m.raceOrder.findIndex(r=>r.id==='player')+1;race.innerHTML=`<div class="race-position"><b>P${position}<small> / ${m.race.entrants.length}</small></b><span>LAP ${Math.max(1,r?.lap??0)} / ${m.raceConfig.laps}</span></div><div class="timing"><span>CURRENT <b>${r?.lap?formatTime(m.race.elapsed-r.lapStart):'—'}</b></span><span>BEST <b>${formatTime(r?.best??0)}</b></span><span>LAST <b>${formatTime(r?.last??0)}</b></span><span class="${r?.valid===false?'invalid':''}">${r?.valid===false?'LAP INVALID':m.race.flag}${r?.penalty?` · +${r.penalty}s`:''}</span>${r?.pit||r?.pitRoute?`<span id="pit-limit" class="${Math.abs(p.speed)>RACE_RULES.pitSpeed?'invalid':''}">PIT LIMIT <b>${Math.round(RACE_RULES.pitSpeed*(s.units==='mph'?2.23694:3.6))} ${s.units}</b></span>${r.pitRoute&&!r.pitValid?'<span class="invalid">PIT ROUTE INVALID</span>':''}`:''}${Number.isFinite(m.race.remaining)?`<span>SESSION <b>${Math.ceil(m.race.remaining/60)} MIN</b></span>`:''}</div>`;}
    text('countdown',m.race.phase==='countdown'?String(Math.ceil(m.race.countdown)):'');const activity=this.root.querySelector('#activity-hud');if(activity)activity.innerHTML=m.activity?`<span class="eyebrow">${esc(m.activity.name)}</span><strong>${m.activity.score>0?Math.round(m.activity.score)+' PTS':formatTime(m.activity.time)}</strong>`:'';
    const telemetry=this.root.querySelector<HTMLElement>('#telemetry');if(telemetry){telemetry.hidden=!s.showTelemetry;telemetry.textContent=`${m.renderer} · ${m.fps.toFixed(0)} FPS\n${m.cells} cells · ${m.drawCalls} draws · ${Math.round(m.triangles/1000)}k triangles\nPhysics ${m.physicsMs.toFixed(2)} ms · Traffic ${m.trafficCount}\nSlip ${p.wheels.map(w=>w.slip.toFixed(2)).join(' / ')}\nLoad ${p.wheels.map(w=>Math.round(w.load)).join(' / ')} N\nTemp ${p.wheels.map(w=>Math.round(w.temperature)).join(' / ')} °C\nWetness ${(m.wetness*100).toFixed(0)}%`;}
  }
}
