/** Generated by scripts/build-textures.mjs. Do not edit by hand. */
export const TEXTURE_ASSET_VERSION='551cbf6d74e06598';
export const textureAssetUrl=(path:string)=>`${path}?v=${TEXTURE_ASSET_VERSION}`;
