/** Generated by scripts/build-textures.mjs. Do not edit by hand. */
export const TEXTURE_ASSET_VERSION='d0e0147642f9b3bd';
export const textureAssetUrl=(path:string)=>`${path}?v=${TEXTURE_ASSET_VERSION}`;
