/** Authored rural infrastructure corridors. Fractions refer to road progress,
 * while spacing and offsets are metres. Props are generated by the world-data
 * worker and merged per cell rather than becoming individual scene meshes. */
export const RURAL_UTILITY_RUNS=[
  {road:'lakeshore',start:.27,end:.84,spacing:78,offset:15},
  {road:'south',start:.08,end:.91,spacing:86,offset:-16},
  {road:'pass',start:.04,end:.55,spacing:82,offset:15},
  {road:'forest',start:.08,end:.91,spacing:74,offset:-14},
] as const;

export const RURAL_FENCE_RUNS=[
  {road:'lakeshore',start:.34,end:.77,spacing:12,offsets:[24]},
  {road:'south',start:.12,end:.88,spacing:12,offsets:[-22,22]},
  {road:'pass',start:.08,end:.43,spacing:11,offsets:[-21]},
  {road:'forest',start:.10,end:.82,spacing:11,offsets:[18]},
] as const;

export const RURAL_FARM_SITES=[
  {road:'lakeshore',at:.47,offset:92,yaw:.10,seed:1101},
  {road:'lakeshore',at:.68,offset:105,yaw:-.16,seed:1102},
  {road:'south',at:.28,offset:94,yaw:.18,seed:1201},
  {road:'south',at:.67,offset:-102,yaw:-.12,seed:1202},
  {road:'pass',at:.24,offset:-88,yaw:.22,seed:1301},
] as const;
